services:
  web:
    image: ghcr.io/woodo260/mather:latest
    ports:
      - "80:80"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_LOG_TO_STDOUT: "true"
    volumes:
      - storage:/rails/storage
    restart: unless-stopped

volumes:
  storage:
